# Generated by Django 3.1.4 on 2020-12-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocenjivanje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content',
            new_name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='prosecnaOcena',
            field=models.FloatField(default=0),
        ),
    ]
