# Generated by Django 3.1.4 on 2021-01-02 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocenjivanje', '0002_auto_20201230_0057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocena',
            old_name='contentt',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
